language: python
cache:
  directories:
  - $HOME/.cache/pip
env:
- IMGAUG_NO_CV2_INSTALLED_CHECK=TRUE
matrix:
  include:
  - python: 2.7
    env: PYTORCH_WHEEL=https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp27-cp27mu-linux_x86_64.whl
  - python: 3.5
    env: PYTORCH_WHEEL=https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp35-cp35m-linux_x86_64.whl
  - python: 3.6
    env: PYTORCH_WHEEL=https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl
  - python: 3.6
    env: TEST_MODE=DOCS
  - python: 3.7
    env: PYTORCH_WHEEL=https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp37-cp37m-linux_x86_64.whl
    dist: xenial
    sudo: true
install:
- pip install --upgrade pip pytest
- if [[ "$TEST_MODE" == "DOCS" ]]; then pip install .; fi
- if [[ -n "$PYTORCH_WHEEL" ]]; then pip install "$PYTORCH_WHEEL" torchvision; fi
- if [[ "$TEST_MODE" != "DOCS" ]]; then pip install .[tests]; fi
- if [[ "$TEST_MODE" != "DOCS" ]]; then pip install "pydocstyle<4.0.0" flake8 flake8-docstrings;
  fi
before_script:
- bash test_mypy.sh
before_install:
- openssl aes-256-cbc -K $MY_KEY -iv $MY_IV -in root_key.enc -out root_key -d
script:
- echo "SCRIPT SECTION"
